#!/bin/bash

DEBUG=0

xset s noblank
xset s off
xset -dpms

#unclutter -idle 0.5 -root &
unclutter -idle 0 -root &

sed -i 's/"exited_cleanly":false/"exited_cleanly":true/' /home/pi/.config/chromium/Default/Preferences
sed -i 's/"exit_type":"Crashed"/"exit_type":"Normal"/' /home/pi/.config/chromium/Default/Preferences

if [ $DEBUG -gt 0 ]; then
  /usr/bin/chromium-browser --kiosk --disk-cache-dir=/dev/null --disk-cache-size=1 --noerrdialogs --disable-infobars --check-for-update-interval=2419200 "http://grafana-01.advan.ca:3000/d/qukMZyqZz/mirror-vert-screen-1?orgId=1&kiosk&refresh=5s" &
else
  /usr/bin/chromium-browser --kiosk --disk-cache-dir=/dev/null --disk-cache-size=1 --noerrdialogs --disable-infobars --check-for-update-interval=2419200 "http://localhost/screen1.html" "http://localhost/screen2.html" "https://calendar.google.com/calendar/u/1/r/agenda?tab=wc" "http://grafana-01.advan.ca:3000/d/qukMZyqZz/mirror-vert-screen-1?orgId=1&kiosk&refresh=5s" "http://localhost/screen3.html" "http://localhost/screen4.html" &

fi

while true; do
   xdotool keydown ctrl+Tab; xdotool keyup ctrl+Tab;
   sleep 60
done
